server:
  port: 8081 # 后端端口

YUNCHAT:
  port: ${YUNCHAT_PORT} # 通信端口
  host: ${YUNCHAT_HOST} # 通信主机
  origin: ${YUNCHAT_ORIGIN} # 跨域设置
  openapi: ${YUNCHAT_OPENAPI} # 开放接口密钥 https://doc.im.xiaokolomi.cn/depoly/openapi.html
  secretKey: ${YUNCHAT_SECRET_KEY} # 服务保护密钥（配置为16位长度的字符串）
  storageMod: ${YUNCHAT_STORAGE_MOD} # 存储模式 0:本地 1:腾讯云COS 2: 阿里云OSS

storage: # 存储配置，若为本地可以不配置
  ali:
    bucket: ${YUNCHAT_STORAGE_ALI_BUCKET} # 阿里云存储桶名称
    endPoint: ${YUNCHAT_STORAGE_ALI_ENDPOINT} # 阿里云存储桶区域
    secretId: ${YUNCHAT_STORAGE_ALI_SECRETID} # 阿里云SecretId
    secretKey: ${YUNCHAT_STORAGE_ALI_SECRETKEY} # 阿里云SecretKey
  tencent:
    region: ${YUNCHAT_STORAGE_TENCENT_REGION} # 腾讯云存储桶区域
    bucket: ${YUNCHAT_STORAGE_TENCENT_BUCKET} # 腾讯云存储桶名称
    secretId: ${YUNCHAT_STORAGE_TENCENT_SECRETID} # 腾讯云SecretId
    secretKey: ${YUNCHAT_STORAGE_TENCENT_SECRETKEY} # 腾讯云SecretKey

spring:
  data:
    redis:
      url: redis://redis-cache:6379
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE} # 文件上传最大大小
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE} # 网络请求最大大小
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME} # 数据库用户
    password: ${SPRING_DATASOURCE_PASSWORD} # 数据库密码
    url: ${SPRING_DATASOURCE_URL} # 数据库连接URL（YUNCHAT为数据库名，必须为YUNCHAT）